### ISSUE TITLE
v1.0.1 gives this error in the log, no brightness changes (W11)

### ISSUE THREAD

**Issue by erak666** [NH5pml30/for-asus-bright-ctrl#1]
[log.txt](https://github.com/NH5pml30/for-asus-bright-ctrl/files/12774205/log.txt)
Hi could you look into this? What might be the issue? Gui shows up, but brightness doesn't change. I am on Windows 11, HDR is off. Thanks

**Comment by NH5pml30** [comment]
Thanks for the report!
1. Could you please check `SecurityCheck` key inside `HKEY_LOCAL_MACHINE\SOFTWARE\ASUS\ASUS System Control Interface\AsusOptimization\ASUS Keyboard Hotkeys` in the Windows Registry? What's its value?
2. If it's 0, please share your current MyASUS app version. Maybe an update broke something

**Comment by erak666** [comment]
It was 1. I changed it to 0 and everything works. Thank you!

**Comment by NH5pml30** [comment]
Yeah, the value should have been set by the installation script, but I guess it wasn't
