### ISSUE TITLE
Install script failing

### ISSUE THREAD

**Issue by timotejroiko** [NH5pml30/for-asus-bright-ctrl#2]
Hello, im trying to install your script and everything works if i manually run the reg file and then run the exe file as admin, but im not managing to run the install script. I have placed the files in a new folder inside Program Files and here's what i get when running the install script (windows 11 23H2 build 22631.2428).

right click install.ps1 -> run with powershell

```powershell
Register-ScheduledTask : The parameter is incorrect.
(9,21):UserId:Zen
At C:\Program Files\Asus Brightness Controls\install.ps1:20 char:9
+         Register-ScheduledTask -Action $action -Trigger $trigger -Tas ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (PS_ScheduledTask:Root/Microsoft/...S_ScheduledTask) [Register-Schedule
   dTask], CimException
    + FullyQualifiedErrorId : HRESULT 0x80070057,Register-ScheduledTask

Start-ScheduledTask : The system cannot find the file specified.
At C:\Program Files\Asus Brightness Controls\install.ps1:21 char:9
+         Start-ScheduledTask -TaskName "for-asus-bright-ctrl"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (PS_ScheduledTask:Root/Microsoft/...S_ScheduledTask) [Start-ScheduledTas
   k], CimException
    + FullyQualifiedErrorId : HRESULT 0x80070002,Start-ScheduledTask
```

run powershell as admin -> cd to folder -> install.ps1

```powershell
PS C:\Program Files\Asus Brightness Controls> .\install.ps1
New-ScheduledTaskAction : Cannot validate argument on parameter 'WorkingDirectory'. The argument is null or empty.
Provide an argument that is not null or empty, and then try the command again.
At C:\Program Files\Asus Brightness Controls\install.ps1:28 char:99
+ ...  "regedit" -Argument "/s install.reg" -WorkingDirectory "$installDir"
+                                                             ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-ScheduledTaskAction], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,New-ScheduledTaskAction

Register-ScheduledTask : Cannot validate argument on parameter 'Action'. The argument is null or empty. Provide an
argument that is not null or empty, and then try the command again.
At C:\Program Files\Asus Brightness Controls\install.ps1:31 char:32
+ Register-ScheduledTask -Action $action -Trigger $trigger -TaskName "f ...
+                                ~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Register-ScheduledTask], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Register-ScheduledTask

Start-ScheduledTask : The system cannot find the file specified.
At C:\Program Files\Asus Brightness Controls\install.ps1:32 char:1
+ Start-ScheduledTask -TaskName "for-asus-bright-ctrl regedit"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (PS_ScheduledTask:Root/Microsoft/...S_ScheduledTask) [Start-ScheduledTas
   k], CimException
    + FullyQualifiedErrorId : HRESULT 0x80070002,Start-ScheduledTask
```

**Comment by NH5pml30** [comment]
Thanks for the report. Do you happen to have a space character in your username? As for the second error, yeah, I guess the script doesn't work if you start it already elevated. I think I'll fix it.

**Comment by timotejroiko** [comment]
Hello, my windows account name does not contain any special characters, its simply `Zen`, it is a local offline account, not a microsoft account.

Also, the first time i ran the script, it worked, but there was something wrong with the reg file task, i dont remember what exactly, then i ran the uninstall script, and after that the install script no longer worked for some reason.

I ended up manually setting up the tasks in the task scheduler and everything is working fine. Really weird for Asus to come up with a parallel brightness system instead of improving the windows one, and then not even include shortcuts for it... so your project is really nice, saves me a lot of time.

**Comment by NH5pml30** [comment]
Sorry for the late response. I really have no idea what could be wrong with the install scripts (other than quotes around the username, but this shouldn't affect your case then), but if you've found a workaround for you then great! I think we can close this issue (?).

And thanks, I hope it doesn't break for you in the future. Nowadays I always enable HDR, and these controls don't work, but the default brightness control seems fine for it. I'll still try to look at the issues here, though.
