### ISSUE TITLE
Direct way to set dimming level

### ISSUE THREAD

**Issue by seerge** [NH5pml30/for-asus-bright-ctrl#3]
Hello,

I was wondering if you managed to dig a bit deeper into this and figure out how exactly MyASUS / Asus Optimization Service sets this brightness level ?

Most of ASUS hardware settings go via Asus ACPI commands. And I strongly suspect this one is also set via another endpoint.

I'm working on an [app for controlling asus laptops](https://github.com/seerge/g-helper), so you can check how other settings are done here
https://github.com/seerge/g-helper/blob/main/app/AsusACPI.cs

Main problem, I don't have an OLED device by myself :) so I can't debug much for it

**Comment by NH5pml30** [comment]
Hello! Unfortunately, I didn't go deeper than the RPC call to `AsusOptimization.exe` and some security checks inside of it I think, so I have no idea what it does internally. If you'd like, I could check some things on my OLED laptop, I guess?
