### ISSUE TITLE
Appears to break after the latest MyASUS update

### ISSUE THREAD

**Issue by mpatelh** [NH5pml30/for-asus-bright-ctrl#4]
Hi NH5pml30! Thanks so much for this utility. I've been using it regularly for at least six months, and it works great.

I recently ran into a forced update to MyASUS 4.0.15.0 (SCI 3.1.29.0), and for-asus-bright-ctrl no longer appears to work. The log.txt spits out the following: 

```
[Error] [OptMan] CheckValid at C:\work\dim\rpc\OptMan.cpp:69: 
> RPC connection is not valid.
[Error] [CRpcThread] checkConnection at C:\work\dim\rpc\main.cpp:54: 
> worker thread cannot operate without a valid RPC connection
[Error] [OptMan] InitRPCConnection at C:\work\dim\rpc\OptMan.cpp:173: 
> could not initialize RPC client: 5
```

The display brightness animation still appears in the top-left of the screen, but the actual brightness of the dimming does not change.

**Comment by NH5pml30** [comment]
Hello, thanks for the report! I'll take a look some time this weekend to see if this can be fixed

**Comment by NH5pml30** [comment]
Hi, I installed the latest update and now have MyASUS version 4.0.15.0 and ASUS System Control Interface version 3.1.29.0, like yours. However I can't reproduce the issue, everything still works for me. You could try to check the following:
- HDR is disabled;
- the registry entry is still there (`HKEY_LOCAL_MACHINE\SOFTWARE\ASUS\ASUS System Control Interface\AsusOptimization\ASUS Keyboard Hotkeys`: `SecurityCheck` must be `0`)

**Comment by mpatelh** [comment]
Thank you so much for looking into this! The SecurityCheck entry was somehow set to 1. Upon flipping it to 0, everything appears to work just fine. I am uncertain as to how that value changed, but it was simple enough to correct.

**Comment by NH5pml30** [comment]
There should be a task in Task Scheduler that runs on each log-in and resets the value back to 0:
![image](https://github.com/NH5pml30/for-asus-bright-ctrl/assets/39946761/084c9374-071f-46b3-b00d-1bcccbe6be6c)
If you encounter this problem in the future, you can try running the install script again from the extracted directory to restore the tasks.
