### ISSUE TITLE
Not working after latest MyAsus update 4.0.23.0

### ISSUE THREAD

**Issue by MysticalCreation** [NH5pml30/for-asus-bright-ctrl#6]
Can't adjust the brightness after recent automatic update of the myasus app.

**Comment by humantorch10** [comment]
@NH5pml30 I have the same issue

**Comment by poojan-solanki** [comment]
Same Issue, Here is the logs after running `uninstall.ps1`, `uninstall.reg`, then `install.reg`, `install.ps1` 

```
[Error] [OptMan] updateRpcConnectStatus at C:\work\dim\rpc\OptMan.cpp:144: 
> RPC connect failed for MyOptSetSplendidDimmingFunc: 87
[Error] [OptMan] CheckValid at C:\work\dim\rpc\OptMan.cpp:69: 
> RPC connection is not valid.
[Error] [CRpcThread] checkConnection at C:\work\dim\rpc\main.cpp:54: 
> worker thread cannot operate without a valid RPC connection
[Error] [OptMan] updateRpcConnectStatus at C:\work\dim\rpc\OptMan.cpp:144: 
> RPC connect failed for MyOptSetSplendidDimmingFunc: 6
[Error] [OptMan] CheckValid at C:\work\dim\rpc\OptMan.cpp:69: 
> RPC connection is not valid.
[Error] [CRpcThread] checkConnection at C:\work\dim\rpc\main.cpp:54: 
> worker thread cannot operate without a valid RPC connection
[Error] [OptMan] updateRpcConnectStatus at C:\work\dim\rpc\OptMan.cpp:144: 
> RPC connect failed for MyOptSetSplendidDimmingFunc: 6
[Error] [OptMan] CheckValid at C:\work\dim\rpc\OptMan.cpp:69: 
> RPC connection is not valid.
[Error] [CRpcThread] checkConnection at C:\work\dim\rpc\main.cpp:54: 
> worker thread cannot operate without a valid RPC connection
[Error] [OptMan] updateRpcConnectStatus at C:\work\dim\rpc\OptMan.cpp:144: 
> RPC connect failed for MyOptSetSplendidDimmingFunc: 6

```

**Comment by poojan-solanki** [comment]
Why no Updates here??

**Comment by Shanyowza** [comment]
Stopped working for me around the same time. Thought it was the hdr but it used to dim even on hdr mode so I have no clue.

**Comment by NH5pml30** [comment]
i'm currently sick i'll deal with this later unfortunately

**Comment by Istria1704** [comment]
Hope you get better soon. Just mentioning here I just discovered your software last week and I unfortunately ran into the same issue. I'll keep checking here for updates. Very weird ASUS does not have this supported natively. In what world is it normal to have to open a program and navigate to the right tab just to adjust brightness.. :o

**Comment by NH5pml30** [comment]
Sorry I've been busy, but I think I found the problem. Please check if this release fixes the issue: https://github.com/NH5pml30/for-asus-bright-ctrl/releases/tag/v1.1.0

**Comment by poojan-solanki** [comment]
Its Working boss. Thankyou❤️

**Comment by NH5pml30** [comment]
Also y'all might want to check out https://github.com/seerge/g-helper, which seems to have much more functionality than this, and it seems to set the flicker-free dimming option fine with the slider. I did have some trouble with the shortcuts/hotkeys, but maybe it's just me

**Comment by MysticalCreation** [comment]
> Also y'all might want to check out https://github.com/seerge/g-helper, which seems to have much more functionality than this, and it seems to set the flicker-free dimming option fine with the slider. I did have some trouble with the shortcuts/hotkeys, but maybe it's just me

Thank you so much for doing this.

btw the g helper doesn't seem to work. I can't find any slider to adjust the brightness with and also keyboard shortcuts don't work

**Comment by MysticalCreation** [comment]
I think it's down again. Asus keeps updating the software and messing up whatever works 🥲

**Comment by poojan-solanki** [comment]
> I think it's down again. Asus keeps updating the software and messing up whatever works 🥲

Did you do ./install.ps1 again after the app was updated. This is needed after every update of MyAsus App.

**Comment by MysticalCreation** [comment]
> > I think it's down again. Asus keeps updating the software and messing up whatever works 🥲
> 
> Did you do ./install.ps1 again after the app was updated. This is needed after every update of MyAsus App.

oh didn't know that. Thank you for the help

**Comment by NH5pml30** [comment]
I don't *think* running installation again is necessary, rebooting or logging out and in again should be enough to re-run the program and registry edits, if I understand everything correctly
